# -*- coding: utf-8 -*-
"""bootstrap-20200516.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C9z1FxFHc9pVh6IqcOw7Ipu0D9DS36v2
"""

import pandas as pd
import numpy as np

1000
100

30%

df = pd.DataFrame({'group': ['A','B'],'leads':[700,300],'sale':[70,40]})

df['conv'] = df['sale'] / df['leads']

df

"""https://www.evanmiller.org/ab-testing/chi-squared.html#!70/700;40/300@95

(p = 0.12)
"""

t1 = pd.DataFrame([0] * (700-70) + [1] * 70)

t1.mean()

t2 = pd.DataFrame([0] * (300-40) + [1] * 40)

t2.mean()

t1['group'] = 'A'

t1

t2['group'] = 'B'

t = pd.concat([t1,t2])

t

t.columns = ['sale','group']

t

t.groupby('group')['sale'].agg(['count','mean']).reset_index()

[0,0,0,1]

(0 + 0 + 0 + 1) / 4

np.mean([0,0,0,1])

df

t

d = pd.DataFrame([1,2,3,4])

d.sample(5,replace=True)

df

a = t.sample(700,replace=True)

a['sale'].mean()

b = t.sample(300,replace=True)

b['sale'].mean()

a = t.sample(700,replace=True)['sale'].mean()
b = t.sample(300,replace=True)['sale'].mean()
print(a,b)

df

diff = np.abs(.1 - 0.133333)

a = t.sample(700,replace=True)['sale'].mean()
b = t.sample(300,replace=True)['sale'].mean()
print(np.abs(a-b))

diff

from tqdm.notebook import tqdm

n = 10000
res = []
for i in tqdm(range(n)):
  a = t.sample(700,replace=True)['sale'].mean()
  b = t.sample(300,replace=True)['sale'].mean()
  res.append(np.abs(a-b) >= diff)

np.mean(res)

from scipy.stats import chi2_contingency

df

df['no_sale'] = df['leads'] - df['sale']

df[['no_sale','sale']]

chi2_contingency(df[['no_sale','sale']],correction=False)

d = pd.DataFrame(np.random.normal(10,3,size=1000))

d[1] = pd.DataFrame(np.random.normal(10,9,size=1000))

d.hist()

d = pd.DataFrame(np.random.normal(10,3,size=1000))

d

d['mean'] = d[0].mean()

d['err'] = (d[0] - d['mean'])**2

np.sqrt(d['err'].mean())

d[0].std()

np.sqrt(d['err'].sum() / (len(d) - 1))

