# -*- coding: utf-8 -*-
"""oil-problem-20200516.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pWNMFUlBJlo57CCNIbbQzdyAMXTlwvZY

# An oil field has 25 wells. Each produces 100 barrels of oil per day. If new wells are drilled the yield of all the wells decreases by 3 barrels per day for each new well. How many wells should be drilled to maximize the number of barrels of oil produced?
"""

25 * 100

(25 + 1)*(100 - 3)

(25 + 2)*(100 - 3*2)

import pandas as pd

df = pd.DataFrame({'wells':range(20)})

df['b'] = (25 + df['wells'])*(100 - 3*df['wells'])

df['b'].plot(grid=True)

df.sort_values('b',ascending=False)

"""f(x) = (25 + x)*(100 - 3*x)  
2500 - 75*x +100*x - 3*x**2  

f(x) = 2500 +25x - 3x**2  

df/dx = 25 - 6x 
25 - 6x = 0  
x = 25/6
"""

25/6

from sympy import *
from sympy.abc import x

expand((25 + x)*(100 - 3*x))

diff(-(x + 25)*(3*x - 100),x)

solve(-6*x + 25)

